trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Deploy
  displayName: Terraform Destroy
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
  - task: TerraformInstaller@0
    displayName: Install Terraform latest
  - task: TerraformTaskV2@2
    displayName: 'Terraform : Init'
    inputs:
      backendServiceArm: 'sc-event-hubs'
      backendAzureRmResourceGroupName: dohoney-devops-rg
      backendAzureRmStorageAccountName: johndohoneytf
      backendAzureRmContainerName: tfstatedohoney
      backendAzureRmKey: terraform.tfstate
  - task: TerraformTaskV2@2
    displayName: 'Terraform : Destroy'
    inputs:
      command: destroy
      environmentServiceNameAzureRM: 'sc-event-hubs'
